services:
  discovery-service:
    build: ./Discovery-Service
    container_name: discovery-dock
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: [ "CMD","curl","-f", "http://localhost:8761/actuator/health" ]
      interval:  10s
      retries:  4

  paiement-service:
    build: ./Paiemant
    container_name: paiemant-dock
    ports:
      - '9090:9090'
    expose:
      - '9090'
    healthcheck:
      test: [ "CMD","curl","-f", "http://localhost:9090/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-dock:8761/eureka
    depends_on:
      discovery-service:
        condition: service_healthy
  etudiant-service:
    build: ./Etudiant
    container_name: etudiant-dock
    ports:
      - '8081:8081'
    expose:
      - '8081'
    healthcheck:
      test: [ "CMD","curl","-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-dock:8761/eureka
    depends_on:
      paiement-service:
        condition: service_healthy
  gateway-service:
    build: ./gateway-service
    container_name: gateway-dock
    ports:
      - '8888:8888'
    expose:
      - '8888'
    healthcheck:
      test: [ "CMD","curl","-f", "http://localhost:8080/actuator/health" ]
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-dock:8761/eureka
    depends_on:
      etudiant-service:
        condition: service_healthy